kind: Deployment
apiVersion: apps/v1
metadata:
  name: frontend
  namespace: expense
  labels:
    project: expense
    component: frontend
    environment: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      project: expense
      component: frontend
      environment: dev
  template:
    metadata:
      labels:
        project: expense
        component: frontend
        environment: dev
    spec:
      containers:
      - name: nginx
        image: joindevops/frontend:1.2.0
---
kind: Service
apiVersion: v1
metadata:
  name: frontend
  namespace: expense
spec:
  type: LoadBalancer
  selector:
    project: expense
    component: frontend
    environment: dev
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080