kind: Deployment
apiVersion: apps/v1
metadata:
  name: backend
  namespace: expense
  labels:
    project: expense
    component: backend
    environment: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      project: expense
      component: backend
      environment: dev
  template:
    metadata:
      labels:
        project: expense
        component: backend
        environment: dev
    spec:
      containers:
      - name: backend
        image: joindevops/backend:1.0.0
---
kind: Service
apiVersion: v1
metadata:
  name: backend
  namespace: expense
spec:
  selector:
    project: expense
    component: backend
    environment: dev
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
