kind: Deployment
apiVersion: apps/v1
metadata:
  name: mysql
  namespace: expense
  labels:
    project: expense
    component: database
    environment: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      project: expense
      component: database
      environment: dev
  template:
    metadata:
      labels:
        project: expense
        component: database
        environment: dev
    spec:
      containers:
      - name: mysql
        image: joindevops/mysql:1.0.0
---
kind: Service
apiVersion: v1
metadata:
  name: mysql
  namespace: expense
spec:
  selector:
    project: expense
    component: database
    environment: dev
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306